### ISSUE TITLE
slow website

### ISSUE THREAD

**Issue by stef-mueller** [ucl-ihi/CodeClub#17]
hi people!
i created a static website using jekyll with domain "http://www.uclhumgen.com/"
there are problems with the site loading very slowly (which I suspect is also influenced by the time in the day). the page is hosted with service ipage.com.

if anybody has experience or some suggestions how to get the website to load quicker, that would be highly appreciated.

stefanie

**Comment by lrj509** [comment]
Hi, not a huge amount of experience with web stuff, but ive found a couple of things that may help.

The three images you have on the first page are quite large files, these could be compressed more with JPEG and also resized to be smaller, as they are not displayed at full size on a normal display.  

Same with the background image, for me the background images are the ones that take the longest to load. Could you compress more with JPEG? 

Luke

**Comment by stef-mueller** [comment]
hey Luke,
thank you for the suggestion! I will definitely look into reducing the image sizes! 
also, big thanks to the code club who looked at this issue today and suggested the chrome-integrated performance-analyser!
best, stefanie
